CC=gcc
RM=rm

all:union union2 enum enum2 pfunc pfunc2 pfunc3

union:union.c 
	$(CC) union.c -o union

union2:union2.c 
	$(CC) union2.c -o union2

enum:enum.c
	$(CC) enum.c -o enum

enum2:enum2.c
	$(CC) enum2.c -o enum2

pfunc:pfunc.c
	$(CC) pfunc.c -o pfunc

pfunc2:pfunc2.c
	$(CC) pfunc2.c -o pfunc2

pfunc3:pfunc3.c
	$(CC) pfunc3.c -o pfunc3

clean:
	$(RM) -f union union2 enum enum2 pfunc pfunc2 pfunc3
