CC=gcc
RM=rm

all:malloc calloc realloc employee mid file

malloc:malloc.c
	$(CC) $^ -o $@

calloc:calloc.c
	$(CC) $^ -o $@

realloc:realloc.c
	$(CC) $^ -o $@

employee:employee.c
	$(CC) $^ -o $@

mid:mid.c
	$(CC) $^ -o $@

file:file.c
	$(CC) $^ -o $@

clean:
	$(RM) -f malloc calloc realloc employee mid file
